import { ELEMENT_TYPES, GRID_WIDTH, GRID_HEIGHT } from './constants.js';

/**
 * Original Boulder Dash cave definitions (16 classic caves A-P)
 * Using a compact representation that will be expanded to the full grid
 */
export const CLASSIC_CAVES = [
    {
        // Cave A: "Intro" - Tutorial level
        name: "INTRO",
        timeLimit: 150,
        diamondsRequired: 10,
        diamondValue: 5,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDBBBDDDDDDDDBBBDDDDDDDDBBBBDDDDDDDDW
WDDDDBBBDDDDDDDDBBBDDDDDDDDBBBBDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDBBBBBBBDDDDDDDDDDDDBBBBBBBBBDDDDDDDW
WDDDBBBBBBBDDDDDDDDDDDDBBBBBBBBBDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDBBBDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDBBBDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDBBBBBBBBBBBBDDDDDDDDDDDDDDDDW
WDDDDDDDDDBBBBBBBBBBBBDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDBBBDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 0
    },
    {
        // Cave B: "Rooms"
        name: "ROOMS",
        timeLimit: 150,
        diamondsRequired: 12,
        diamondValue: 10,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDWDDDDDWDDDDDWDDDDDWDDDDDWDDDDDDDDDEW
WDDDWDDBDDWDDBDDWDDBDDWDDBDDWDDDDDDDDDW
WDDDWDDDDDWDDDDDWDDDDDWDDDDDWDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDDDDDDDDW
WDDDDWDDDDDDDDWDDDDDDDDWDDDDDDDDDDDDDDDW
WDBDDWDDBBDDDDWDDBBDDDDWDDDDDDDDDDDDDDDW
WDDDDWDDDDDDDDWDDDDDDDDWDDDDDDDDDDDDDDDW
WDDDDDWWWWWWWWWWWWWWWWWWWWWWWDDDDDDDDDW
WDDDDDDDDWDDDDDWDDDDDWDDDDDWDDDDDDDDDDDW
WDDBDDDDDWDDBDDWDDBDDWDDBDDWDDDDDDDDDDDW
WDDDDDDDDWDDDDDWDDDDDWDDDDDWDDDDDDDDDDDW
WDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDDW
WDDDDDDWDDDDDDWDDDDDDWDDDDDDWDDDDDDDDDDDW
WDDBDDDWDDBBDDWDDBBDDWDDBBDDWDDDDDDDDDDDW
WDDDDDDWDDDDDDWDDDDDDWDDDDDDWDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 1
    },
    {
        // Cave C: "Maze"
        name: "MAZE",
        timeLimit: 180,
        diamondsRequired: 15,
        diamondValue: 12,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDWDDDDDWDDDDDWDDDDDWDDDDDWDDDDDDDDDW
WDWWWWWWWDWWWWWDWWWWWDWWWWWDWWWWWWWWWDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDDDDDDDEW
WWWDWWWDWWWDWWWDWWWDWWWDWWWDWWWWWWWWWWDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDDDDDDDDDW
WDWWWWWWWDWWWWWDWWWWWDWWWWWDWWWWWWWWWDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDDDDDDDDDW
WWWDWWWDWWWDWWWDWWWDWWWDWWWDWWWWWWWWWWDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDDBBBDDDDW
WDWWWWWWWDWWWWWDWWWWWDWWWWWDWWWWBBBBWDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDDBBBDDDDW
WWWDWWWDWWWDWWWDWWWDWWWDWWWDWWWWWWWWWWDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDDDDDDDDDW
WDWWWWWWWDWWWWWDWWWWWDWWWWWDWWWWWWWWWDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 2
    },
    {
        // Cave D: "Butterflies"
        name: "BUTTERFLIES",
        timeLimit: 120,
        diamondsRequired: 10,
        diamondValue: 15,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDWWWWWDDDDDDDWWWWWDDDDDDDWWWWWDDDDW
WDDDDDWDDDWDDDDDDDWDDDWDDDDDDDWDDDWDDDDW
WDDDDDWDFDWDDDDDDDWDFDWDDDDDDDWDFDWDDDDW
WDDDDDWDDDWDDDDDDDWDDDWDDDDDDDWDDDWDDDDW
WDDDDDWWWWWDDDDDDDWWWWWDDDDDDDWWWWWDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBBDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBBDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDWWWWWDDDDDDDWWWWWDDDDDDDWWWWWDDDDW
WDDDDDWDDDWDDDDDDDWDDDWDDDDDDDWDDDWDDDDW
WDDDDDWDFDWDDDDDDDWDFDWDDDDDDDWDFDWDDDDW
WDDDDDWDDDWDDDDDDDWDDDWDDDDDDDWDDDWDDDDW
WDDDDDWWWWWDDDDDDDWWWWWDDDDDDDWWWWWDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 3
    },
    {
        // Cave E: "Guards"
        name: "GUARDS",
        timeLimit: 150,
        diamondsRequired: 18,
        diamondValue: 8,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDW
WDDDWDDDDDDDDDFDDDDDDDDDFDDDDDDDDDWDDDDW
WDDDWDDDBBBBBBBBBBBBBBBBBBBBBBDDDWDDDDW
WDDDWDDDBBBBBBBBBBBBBBBBBBBBBBDDDWDDDDW
WDDDWDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWDDDDW
WDDDWDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWDDDDW
WDDDWDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWDDDDW
WDDDWDDDBBBBBBBBBBBBBBBBBBBBBBDDDWDDDDW
WDDDWDDDBBBBBBBBBBBBBBBBBBBBBBDDDWDDDDW
WDDDWDDDDDDDDDFDDDDDDDDDFDDDDDDDDDWDDDDW
WDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 2
    },
    {
        // Cave F: "Firefly Dens"
        name: "FIREFLY DENS",
        timeLimit: 150,
        diamondsRequired: 20,
        diamondValue: 10,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDWWWWWWWDDDWWWWWWWDDDWWWWWWWDDDDDDDW
WDDDWDDDDDWDDDWDDDDDWDDDWDDDDDWDDDDDDDW
WDDDWDDFDDWDDDWDDFDDWDDDWDDFDDWDDDDDDDW
WDDDWDDDDDWDDDWDDDDDWDDDWDDDDDWDDDDDDDW
WDDDWWWWWWWDDDWWWWWWWDDDWWWWWWWDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDW
WDDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDWWWWWWWDDDWWWWWWWDDDWWWWWWWDDDDDDDW
WDDDWDDDDDWDDDWDDDDDWDDDWDDDDDWDDDDDDDW
WDDDWDDFDDWDDDWDDFDDWDDDWDDFDDWDDDDDDDW
WDDDWDDDDDWDDDWDDDDDWDDDWDDDDDWDDDDDDDW
WDDDWWWWWWWDDDWWWWWWWDDDWWWWWWWDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 4
    },
    {
        // Cave G: "Amoeba"
        name: "AMOEBA",
        timeLimit: 200,
        diamondsRequired: 25,
        diamondValue: 5,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDWWWWWWWWWWWWWDDDDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDDW
WDDDDDDDDDDDWWWWWWWWWWWWWDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDW
WDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 5
    },
    {
        // Cave H: "Enchanted Wall"
        name: "ENCHANTED WALL",
        timeLimit: 180,
        diamondsRequired: 22,
        diamondValue: 12,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDW
WDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDW
WDDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 3
    },
    {
        // Cave I: "Greed"
        name: "GREED",
        timeLimit: 100,
        diamondsRequired: 30,
        diamondValue: 6,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDBBBBBBBBBBBBBDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 6
    },
    {
        // Cave J: "Tracks"
        name: "TRACKS",
        timeLimit: 180,
        diamondsRequired: 16,
        diamondValue: 15,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWW
WDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWW
WDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDW
WDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWW
WDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWW
WDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWDDDWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 4
    },
    {
        // Cave K: "Crowd"
        name: "CROWD",
        timeLimit: 150,
        diamondsRequired: 24,
        diamondValue: 10,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDWWWWWWWWWDDDDDDDDDDDWWWWWWWWWWDDDDW
WDDDWDDDDDDDWDDDDDFDDDDDWDDDDDDDWDDDDDDW
WDDDWDDBBBDDWDDDDDDDDDDDWDDBBBDDWDDDDDDW
WDDDWDDBBBDDWDDDDDFDDDDDWDDBBBDDWDDDDDDW
WDDDWDDDDDDDWDDDDDDDDDDDWDDDDDDDWDDDDDDW
WDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDW
WDDDWDDDDDDDWDDDDDFDDDDDWDDDDDDDWDDDDDDW
WDDDWDDBBBDDWDDDDDDDDDDDWDDBBBDDWDDDDDDW
WDDDWDDBBBDDWDDDDDFDDDDDWDDBBBDDWDDDDDDW
WDDDWDDDDDDDWDDDDDDDDDDDWDDDDDDDWDDDDDDW
WDDDWWWWWWWWWDDDDDDDDDDDWWWWWWWWWWDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 5
    },
    {
        // Cave L: "Walls"
        name: "WALLS",
        timeLimit: 200,
        diamondsRequired: 20,
        diamondValue: 12,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WWWWWWWWWWWWDDDDDDDDDDDWWWWWWWWWWWWWWDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWWWWWWWWWWWWWWDDDDWWWWWWWWWWWWWWWWWDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWWWWWWWWWWWWWWDDDDWWWWWWWWWWWWWWWWWDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWDDDDDDDDDDDWWWWWWWWWWWWWWDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWWWWWWWWWWWWWWDDDDWWWWWWWWWWWWWWWWWDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDBBBBBBBBBBBBBBBBBBBBBBBBBBDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 4
    },
    {
        // Cave M: "Apocalypse"
        name: "APOCALYPSE",
        timeLimit: 120,
        diamondsRequired: 28,
        diamondValue: 8,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDW
WDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDW
WDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDFDFDFDFDFDFDFDFDFDFDFDFDFDFDFDFDFDFDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDW
WDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDW
WDDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 8
    },
    {
        // Cave N: "Zigzag"
        name: "ZIGZAG",
        timeLimit: 180,
        diamondsRequired: 18,
        diamondValue: 14,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDWDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWDDW
WDDDDDWDDDDDDDDDDDDDDDDDDDDDDDDDDDWDDDDDW
WDDDDDDDWDDDDDDDDDDDDDDDDDDDDDDDWDDDDDDDW
WDDDDDDDDDWDDDDDDDDDDDDDDDDDDDWDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDDDDDWDDDDDDDDDDDW
WDDDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDWDDDDDDDWDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDWDDDWDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDWDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDWDDDWDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDWDDDDDDDWDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDWDDDDDDDDDDDWDDDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDDDDDWDDDDDDDDDDDW
WDDDDDDDDDWDDDDDDDDDDDDDDDDDDDWDDDDDDDDDW
WDDDDDDDWDDDDDDDDDDDDDDDDDDDDDDDWDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 3
    },
    {
        // Cave O: "Funnel"
        name: "FUNNEL",
        timeLimit: 150,
        diamondsRequired: 26,
        diamondValue: 9,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBW
WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWDDDW
WDDDWDDDDDDDDDDDDDDDDDDDDDDDDDDDDDWDDDDDW
WDDDDDWDDDDDDDDDDDDDDDDDDDDDDDDDWDDDDDDDW
WDDDDDDDWDDDDDDDDDDDDDDDDDDDDDWDDDDDDDDDW
WDDDDDDDDDWDDDDDDDDDDDDDDDDDWDDDDDDDDDDDW
WDDDDDDDDDDDWDDDDDDDDDDDDDWDDDDDDDDDDDDDW
WDDDDDDDDDDDDDWDDDDDDDDDWDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDWDDDDDWDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDWDWDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 5
    },
    {
        // Cave P: "Vertigo"
        name: "VERTIGO",
        timeLimit: 200,
        diamondsRequired: 30,
        diamondValue: 10,
        pattern: `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDEW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDW
WDBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDDW
WDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
        `,
        enemies: 6
    }
];

/**
 * Parse a pattern string into a grid
 * W = Wall, P = Player, E = Exit, D = Diamond, B = Boulder, F = Firefly (enemy), d = dirt, . = empty
 */
export function parsePattern(pattern, width, height) {
    const lines = pattern.trim().split('\n').map(line => line.trim());
    const grid = [];
    let playerPos = null;
    let exitPos = null;
    const enemies = [];
    const diamonds = [];
    
    for (let y = 0; y < Math.min(height, lines.length); y++) {
        const row = [];
        const line = lines[y] || '';
        
        for (let x = 0; x < width; x++) {
            const char = line[x] || 'd';
            let cell = ELEMENT_TYPES.DIRT;
            
            switch (char) {
                case 'W':
                    cell = ELEMENT_TYPES.WALL;
                    break;
                case 'P':
                    cell = ELEMENT_TYPES.PLAYER;
                    playerPos = { x, y };
                    break;
                case 'E':
                    cell = ELEMENT_TYPES.EXIT;
                    exitPos = { x, y };
                    break;
                case 'D':
                    cell = ELEMENT_TYPES.DIAMOND;
                    diamonds.push({ x, y });
                    break;
                case 'B':
                case 'b':
                    cell = ELEMENT_TYPES.BOULDER;
                    break;
                case 'F':
                case 'f':
                    cell = ELEMENT_TYPES.ENEMY;
                    enemies.push({ x, y });
                    break;
                case 'd':
                    cell = ELEMENT_TYPES.DIRT;
                    break;
                case '.':
                    cell = ELEMENT_TYPES.EMPTY;
                    break;
            }
            
            row.push(cell);
        }
        
        grid.push(row);
    }
    
    return { grid, playerPos, exitPos, enemies, diamonds };
}
